title: Amba Mohan
description: Identity and Access Management Specialist
#show_downloads: true
google_analytics:
#theme: jekyll-theme-cayman
theme: jekyll-theme-leap-day
github:
  is_project_page: false
