title: Amba Mohan
description: Identity and Access Management Specialist
linkedin_url: https://www.linkedin.com/in/amba-mohan-588b01b3/
#show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
#theme: jekyll-theme-leap-day
github:
  is_project_page: false
